export const homeObjOne = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Offline Dating',
    headline: 'NECTER',
    description: 'All of the best features of online and offline dating. All of the best features of online and offline dating.',
    buttonLable: 'Get Started',
    imgStart: false,
    img: require('../../images/online-dating.svg').default,
    alt: 'Car',
    dark: false,
    primary: true,
    darkText: true,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Offline Dating',
    headline: 'NECTER',
    description: 'All of the best features of online and offline dating. All of the best features of online and offline dating.',
    buttonLable: 'Get Started',
    imgStart: true,
    img: require('../../images/online-dating.svg').default,
    alt: 'Car',
    dark: false,
    primary: true,
    darkText: false,
}

export const homeObjThree = {
    id: 'services',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Offline Dating',
    headline: 'NECTER',
    description: 'All of the best features of online and offline dating. All of the best features of online and offline dating.',
    buttonLable: 'Get Started',
    imgStart: false,
    img: require('../../images/online-dating.svg').default,
    alt: 'Car',
    dark: false,
    primary: true,
    darkText: true,
}